export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
export const SET_IS_SYNCED = 'SET_IS_SYNCED'
export const SET_SYNC_ERROR = 'SET_SYNC_ERROR'
export const SET_SYNC_TIME = 'SET_SYNC_TIME'

export const SET_POSTS = 'SET_POSTS'
export const SET_POST = 'SET_POST'
export const NEW_POST = 'NEW_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'

export const SET_AUTHORS = 'SET_AUTHORS'
export const SET_AUTHOR = 'SET_AUTHOR'
export const NEW_AUTHOR = 'NEW_AUTHOR'
export const UPDATE_AUTHOR = 'UPDATE_AUTHOR'
export const DELETE_AUTHOR = 'DELETE_AUTHOR'

export const SET_APPCONFIG = 'SET_APPCONFIG'
export const SET_APPFIREWALL = 'SET_APPFIREWALL'
